# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1127, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1131, 601))
        self.frame.setStyleSheet("background-color:#d1d8e0;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1131, 80))
        self.frame_2.setStyleSheet("background-color:#9980FA;\n"
"color:#009432;\n"
"text-align:center;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(390, 10, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#5758BB;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(350, 80, 461, 181))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("imgonline-com-ua-Transparent-backgr-48tgqomMjDUEwY.png"))
        self.label_2.setObjectName("label_2")
        self.admin_login = QtWidgets.QPushButton(self.frame)
        self.admin_login.setGeometry(QtCore.QRect(30, 350, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.admin_login.setFont(font)
        self.admin_login.setStyleSheet("QPushButton{background-color:#5758BB;\n"
"color:white;\n"
"border: 2px solid white;\n"
"border-radius:10px;}\n"
"QPushButton:pressed{background-color:darkgreen;\n"
"color:white;\n"
"border: 2px solid white;\n"
"border-radius:10px;}")
        self.admin_login.setObjectName("admin_login")
        self.user_login = QtWidgets.QPushButton(self.frame)
        self.user_login.setGeometry(QtCore.QRect(260, 350, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.user_login.setFont(font)
        self.user_login.setStyleSheet("QPushButton{background-color:#5758BB;\n"
"color:white;\n"
"border: 2px solid white;\n"
"border-radius:10px;}\n"
"QPushButton:pressed{background-color:darkgreen;\n"
"color:white;\n"
"border: 2px solid white;\n"
"border-radius:10px;}")
        self.user_login.setObjectName("user_login")
        self.register_2 = QtWidgets.QPushButton(self.frame)
        self.register_2.setGeometry(QtCore.QRect(710, 350, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.register_2.setFont(font)
        self.register_2.setStyleSheet("QPushButton{background-color:#5758BB;\n"
"color:white;\n"
"border: 2px solid white;\n"
"border-radius:10px;}\n"
"QPushButton:pressed{background-color:darkgreen;\n"
"color:white;\n"
"border: 2px solid white;\n"
"border-radius:10px;}")
        self.register_2.setObjectName("register_2")
        self.exit = QtWidgets.QPushButton(self.frame)
        self.exit.setGeometry(QtCore.QRect(940, 350, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.exit.setFont(font)
        self.exit.setStyleSheet("QPushButton{background-color:#5758BB;\n"
"color:white;\n"
"border: 2px solid white;\n"
"border-radius:10px;}\n"
"QPushButton:pressed{background-color:darkgreen;\n"
"color:white;\n"
"border: 2px solid white;\n"
"border-radius:10px;}")
        self.exit.setObjectName("exit")
        self.babk_button = QtWidgets.QPushButton(self.frame)
        self.babk_button.setGeometry(QtCore.QRect(480, 350, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.babk_button.setFont(font)
        self.babk_button.setStyleSheet("QPushButton{background-color:#5758BB;\n"
"color:white;\n"
"border: 2px solid white;\n"
"border-radius:10px;}\n"
"QPushButton:pressed{background-color:darkgreen;\n"
"color:white;\n"
"border: 2px solid white;\n"
"border-radius:10px;}")
        self.babk_button.setObjectName("babk_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Dynamo-Bank"))
        self.admin_login.setText(_translate("MainWindow", "Администратор"))
        self.user_login.setText(_translate("MainWindow", "Пользователь"))
        self.register_2.setText(_translate("MainWindow", "Регистрация"))
        self.exit.setText(_translate("MainWindow", "Выход"))
        self.babk_button.setText(_translate("MainWindow", "Управление"))
