# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'survey.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1126, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1131, 601))
        self.frame.setStyleSheet("background-color:#d1d8e0;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1131, 80))
        self.frame_2.setStyleSheet("background-color:#9980FA;\n"
"color:white;\n"
"text-align:center;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(390, 10, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#black;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(470, 590, 461, 181))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("imgonline-com-ua-Transparent-backgr-48tgqomMjDUEwY.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(320, 80, 461, 181))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("imgonline-com-ua-Transparent-backgr-48tgqomMjDUEwY.png"))
        self.label_3.setObjectName("label_3")
        self.send_button = QtWidgets.QPushButton(self.frame)
        self.send_button.setGeometry(QtCore.QRect(490, 490, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.send_button.setFont(font)
        self.send_button.setStyleSheet("QPushButton{background-color:#5758BB;\n"
"color:white;\n"
"border-radius: 10px;}\n"
"QPushButton:pressed{\n"
"background-color:darkgreen;\n"
"color:white;\n"
"border-radius: 10px;\n"
"}")
        self.send_button.setObjectName("send_button")
        self.byn_usd = QtWidgets.QComboBox(self.frame)
        self.byn_usd.setGeometry(QtCore.QRect(110, 310, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.byn_usd.setFont(font)
        self.byn_usd.setStyleSheet("background-color:#5758BB;\n"
"color:white;\n"
"border-radius: 10px;")
        self.byn_usd.setObjectName("byn_usd")
        self.byn_usd.addItem("")
        self.byn_usd.addItem("")
        self.byn_eur = QtWidgets.QComboBox(self.frame)
        self.byn_eur.setGeometry(QtCore.QRect(270, 310, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.byn_eur.setFont(font)
        self.byn_eur.setStyleSheet("background-color:#5758BB;\n"
"color:white;\n"
"border-radius: 10px;")
        self.byn_eur.setObjectName("byn_eur")
        self.byn_eur.addItem("")
        self.byn_eur.addItem("")
        self.byn_rub = QtWidgets.QComboBox(self.frame)
        self.byn_rub.setGeometry(QtCore.QRect(430, 310, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.byn_rub.setFont(font)
        self.byn_rub.setStyleSheet("background-color:#5758BB;\n"
"color:white;\n"
"border-radius: 10px;")
        self.byn_rub.setObjectName("byn_rub")
        self.byn_rub.addItem("")
        self.byn_rub.addItem("")
        self.eur_usd = QtWidgets.QComboBox(self.frame)
        self.eur_usd.setGeometry(QtCore.QRect(590, 310, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.eur_usd.setFont(font)
        self.eur_usd.setStyleSheet("background-color:#5758BB;\n"
"color:white;\n"
"border-radius: 10px;")
        self.eur_usd.setObjectName("eur_usd")
        self.eur_usd.addItem("")
        self.eur_usd.addItem("")
        self.rub_usd = QtWidgets.QComboBox(self.frame)
        self.rub_usd.setGeometry(QtCore.QRect(750, 310, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rub_usd.setFont(font)
        self.rub_usd.setStyleSheet("background-color:#5758BB;\n"
"color:white;\n"
"border-radius: 10px;")
        self.rub_usd.setObjectName("rub_usd")
        self.rub_usd.addItem("")
        self.rub_usd.addItem("")
        self.rub_eur = QtWidgets.QComboBox(self.frame)
        self.rub_eur.setGeometry(QtCore.QRect(900, 310, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rub_eur.setFont(font)
        self.rub_eur.setStyleSheet("background-color:#5758BB;\n"
"color:white;\n"
"border-radius: 10px;")
        self.rub_eur.setObjectName("rub_eur")
        self.rub_eur.addItem("")
        self.rub_eur.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Dynamo-Bank"))
        self.send_button.setText(_translate("MainWindow", "Отправить"))
        self.byn_usd.setItemText(0, _translate("MainWindow", "BYN"))
        self.byn_usd.setItemText(1, _translate("MainWindow", "USD"))
        self.byn_eur.setItemText(0, _translate("MainWindow", "BYN"))
        self.byn_eur.setItemText(1, _translate("MainWindow", "EUR"))
        self.byn_rub.setItemText(0, _translate("MainWindow", "BYN"))
        self.byn_rub.setItemText(1, _translate("MainWindow", "RUB"))
        self.eur_usd.setItemText(0, _translate("MainWindow", "EUR"))
        self.eur_usd.setItemText(1, _translate("MainWindow", "USD"))
        self.rub_usd.setItemText(0, _translate("MainWindow", "RUB"))
        self.rub_usd.setItemText(1, _translate("MainWindow", "USD"))
        self.rub_eur.setItemText(0, _translate("MainWindow", "RUB"))
        self.rub_eur.setItemText(1, _translate("MainWindow", "EUR"))
